[build]
  command = "npm run build"       # no next export
  publish = "out"                 # Next.js 14 static export folder
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
